server:
  port: 8080
  servlet:
    context-path: /  #该属性默认值为/，即为访问localhost:8080/即可访问到

spring:
  devtools:
    restart:
      enabled: true #热加载
  datasource:
    url: jdbc:mysql://localhost:3306/shabby?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    name: shabby
    #druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat   #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有:监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
    maxActive: 20   #连接池的最大值，同一时间可以从池分配的最多连接数量，0时无限制
    initialSize: 1    #连接初始值，连接池启动时创建的连接数量的初始值
    maxWait: 60000    #获取连接至最大等待时间
    minIdle: 1    #最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请,ps.最小连接池数量
    timeBetweenEvictionRunsMillis: 60000    #1) 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒2) testWhileIdle的判断依据
    minEvictableIdleTimeMillis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: select 'x'   #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
    testWhileIdle: true   #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testOnBorrow: false   #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。可以防止取到的连接不可用
    testOnReturn: false   #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。可以防止取到的连接不可用
    poolPreparedStatements: true    #是否对已备语句进行池管理（布尔值），是否对PreparedStatement进行缓存,mysql下建议关闭
    maxOpenPreparedStatements: 20   #要使用ps cache，该值需要大于0，当该值大于0的时候，poolPreparedStatements自动触发修改为true；指定每个连接上PSCache的大小
  thymeleaf:
    cache: false   #模板缓存
    check-template: true    #检测模板是否存在
    servlet:
      content-type: text/html   #
    enabled: true   #Enable MVC Thymeleaf view resolution
    encoding: utf-8
    excluded-view-names:    #Comma-separated list of view names that should be excluded from resolution
    mode: HTML5   #Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    #prefix: classpath:**/templates/
    #suffix: .html
    template-resolver-order:
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
mybatis:
  mapper-locations: classpath:**/mapper/*Mapper.xml
  #扫描实体类,多个由逗号或者分号分开
  type-aliases-package: com.jxl.shabby_for_me.common.entity.*
  #刷新mapper,调试器
  refreh-mapper: true
